// Parity test between `computeBuckets` (this file's live re-derivation of
// `weekend_bucket` / the school-holiday flags, run in the browser against
// *today*) and `automation/normalize.py#_bucketize` (the pipeline's source of
// truth, run once a week). See `automation/tests/test_bucket_parity.py` for
// the Python half of this pair — both load the SAME fixture,
// `automation/tests/fixtures/bucket_cases.json`, generated by running the
// Python implementation (see that file's docstring for the regeneration
// snippet). A case with a `known_divergence` field is a confirmed, documented
// disagreement between the two sides rather than a bug in this test.
//
// The fixture also embeds the two school calendars
// (`holidays_nl`/`holidays_fr` -- `config.SCHOOL_HOLIDAYS_NL`/`_FR` verbatim,
// in the same shape `publish.build_payload` ships as `school_holidays_nl`/
// `_fr`). Read them from here rather than hand-copying config.py's tables
// into this file a third time -- that hand-maintained copy is exactly the
// drift this test exists to prevent, and the Python side's
// `test_fixture_calendars_match_config` already asserts the embedded copy
// matches config.py.
//
// Loaded via `fs.readFileSync` + `import.meta.url` rather than a JSON import:
// the fixture lives outside `frontend/src` (tsconfig's `include` is just
// `["src"]`), so a relative `import ... from "../../../automation/..."` would
// need `resolveJsonModule` to resolve a path tsc doesn't compile.
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { describe, expect, it } from "vitest";
import type { Activity, SchoolHoliday } from "../types";
import { computeBuckets, type BelgiumDate } from "./buckets";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FIXTURE_PATH = path.resolve(
  __dirname,
  "../../../automation/tests/fixtures/bucket_cases.json",
);

interface Case {
  name: string;
  today: string;
  activity: Partial<Activity>;
  expected: {
    weekend_bucket: string[];
    school_holiday_nl: string | null;
    school_holiday_fr: string | null;
    in_school_holiday: boolean;
  };
  known_divergence?: string;
}

interface Fixture {
  holidays_nl: SchoolHoliday[];
  holidays_fr: SchoolHoliday[];
  cases: Case[];
}

const fixture: Fixture = JSON.parse(readFileSync(FIXTURE_PATH, "utf-8"));
const { holidays_nl: SCHOOL_HOLIDAYS_NL, holidays_fr: SCHOOL_HOLIDAYS_FR, cases } = fixture;

function toBelgiumDate(iso: string): BelgiumDate {
  const [y, m, d] = iso.split("-").map(Number);
  return [y, m, d];
}

function act(over: Partial<Activity>): Activity {
  return {
    date_kind: "single",
    all_day: false,
    date_start: null,
    date_end: null,
    occurrences: [],
    ...over,
  } as Activity;
}

describe("bucket parity fixture (shared with automation/tests/test_bucket_parity.py)", () => {
  it("has at least 25 cases", () => {
    expect(cases.length).toBeGreaterThanOrEqual(25);
  });

  it("embeds both school calendars", () => {
    expect(SCHOOL_HOLIDAYS_NL.length).toBeGreaterThan(0);
    expect(SCHOOL_HOLIDAYS_FR.length).toBeGreaterThan(0);
  });

  for (const c of cases) {
    const run = () => {
      const today = toBelgiumDate(c.today);
      const activity = act(c.activity);
      const result = computeBuckets(activity, today, SCHOOL_HOLIDAYS_NL, SCHOOL_HOLIDAYS_FR);
      expect([...result.weekend_bucket].sort()).toEqual([...c.expected.weekend_bucket].sort());
      expect(result.school_holiday_nl).toBe(c.expected.school_holiday_nl);
      expect(result.school_holiday_fr).toBe(c.expected.school_holiday_fr);
      expect(result.in_school_holiday).toBe(c.expected.in_school_holiday);
    };

    if (c.known_divergence) {
      it.skip(`${c.name} [SKIPPED - known divergence: ${c.known_divergence}]`, run);
    } else {
      it(c.name, run);
    }
  }
});
