// Parity test between `computeBuckets` (this file's live re-derivation of
// `weekend_bucket` / the school-holiday flags, run in the browser against
// *today*) and `automation/normalize.py#_bucketize` (the pipeline's source of
// truth, run once a week). See `automation/tests/test_bucket_parity.py` for
// the Python half of this pair — both load the SAME fixture,
// `automation/tests/fixtures/bucket_cases.json`, generated by running the
// Python implementation (see that file's docstring for the regeneration
// snippet). A case with a `known_divergence` field is a confirmed, documented
// disagreement between the two sides rather than a bug in this test.
//
// Loaded via `fs.readFileSync` + `import.meta.url` rather than a JSON import:
// the fixture lives outside `frontend/src` (tsconfig's `include` is just
// `["src"]`), so a relative `import ... from "../../../automation/..."` would
// need `resolveJsonModule` to resolve a path tsc doesn't compile.
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { describe, expect, it } from "vitest";
import type { Activity, SchoolHoliday } from "../types";
import { computeBuckets, type BelgiumDate } from "./buckets";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FIXTURE_PATH = path.resolve(
  __dirname,
  "../../../automation/tests/fixtures/bucket_cases.json",
);

interface Case {
  name: string;
  today: string;
  activity: Partial<Activity>;
  expected: {
    weekend_bucket: string[];
    school_holiday_nl: string | null;
    school_holiday_fr: string | null;
    in_school_holiday: boolean;
  };
  known_divergence?: string;
}

const cases: Case[] = JSON.parse(readFileSync(FIXTURE_PATH, "utf-8"));

function toBelgiumDate(iso: string): BelgiumDate {
  const [y, m, d] = iso.split("-").map(Number);
  return [y, m, d];
}

/** Holidays in the fixture activities are given by name+start+end directly on
 *  the case; but `_bucketize`/`computeBuckets` both consult the GLOBAL
 *  calendars (`config.SCHOOL_HOLIDAYS_NL/_FR`), not a per-activity field. So
 *  the parity test needs the same two calendars the fixture was generated
 *  against — copied here (see `automation/config.py`) rather than duplicating
 *  the whole config module in a browser test. */
const SCHOOL_HOLIDAYS_NL: SchoolHoliday[] = [
  { name: "zomervakantie", start: "2026-07-01", end: "2026-08-31" },
  { name: "herfstvakantie", start: "2026-10-26", end: "2026-11-01" },
  { name: "kerstvakantie", start: "2026-12-21", end: "2027-01-04" },
  { name: "krokusvakantie", start: "2027-02-15", end: "2027-02-21" },
  { name: "paasvakantie", start: "2027-03-29", end: "2027-04-11" },
  { name: "zomervakantie", start: "2027-07-01", end: "2027-08-31" },
];

const SCHOOL_HOLIDAYS_FR: SchoolHoliday[] = [
  { name: "grandes vacances", start: "2026-07-01", end: "2026-08-23" },
  { name: "conge d'automne", start: "2026-10-19", end: "2026-11-01" },
  { name: "vacances d'hiver", start: "2026-12-21", end: "2027-01-03" },
  { name: "conge de detente", start: "2027-02-22", end: "2027-03-07" },
  { name: "vacances de printemps", start: "2027-04-26", end: "2027-05-09" },
  { name: "grandes vacances", start: "2027-07-03", end: "2027-08-22" },
];

function act(over: Partial<Activity>): Activity {
  return {
    date_kind: "single",
    all_day: false,
    date_start: null,
    date_end: null,
    occurrences: [],
    ...over,
  } as Activity;
}

describe("bucket parity fixture (shared with automation/tests/test_bucket_parity.py)", () => {
  it("has at least 25 cases", () => {
    expect(cases.length).toBeGreaterThanOrEqual(25);
  });

  for (const c of cases) {
    const run = () => {
      const today = toBelgiumDate(c.today);
      const activity = act(c.activity);
      const result = computeBuckets(activity, today, SCHOOL_HOLIDAYS_NL, SCHOOL_HOLIDAYS_FR);
      expect([...result.weekend_bucket].sort()).toEqual([...c.expected.weekend_bucket].sort());
      expect(result.school_holiday_nl).toBe(c.expected.school_holiday_nl);
      expect(result.school_holiday_fr).toBe(c.expected.school_holiday_fr);
      expect(result.in_school_holiday).toBe(c.expected.in_school_holiday);
    };

    if (c.known_divergence) {
      it.skip(`${c.name} [SKIPPED - known divergence: ${c.known_divergence}]`, run);
    } else {
      it(c.name, run);
    }
  }
});
