import type { Category, FeatureTag, PlaceKind } from "../types";

export const PLACE_KIND_LABELS: Record<PlaceKind, string> = {
  museum: "Museum",
  zoo: "Zoo & animals",
  provincial_domain: "Provincial domain",
  speelbos: "Play forest",
  playground_indoor: "Indoor playground",
  playground_outdoor: "Outdoor playground",
  multimove: "MultiMove trail",
  zomerbar: "Zomerbar",
  playground_restaurant: "Eat & play",
  farm: "Farm",
  attraction_park: "Theme park",
  castle: "Castle",
  other: "Other",
};

export const PLACE_KIND_EMOJI: Record<PlaceKind, string> = {
  museum: "🏛️",
  zoo: "🦩",
  provincial_domain: "🌳",
  speelbos: "🌲",
  playground_indoor: "🧗",
  playground_outdoor: "🛝",
  multimove: "🤸",
  zomerbar: "🍹",
  playground_restaurant: "🍽️",
  farm: "🐐",
  attraction_park: "🎢",
  castle: "🏰",
  other: "📍",
};

export const CATEGORY_LABELS: Record<Category, string> = {
  festival: "Festival",
  kermis_carnaval: "Kermis & carnaval",
  theatre_puppetry: "Theatre & puppetry",
  music_concert: "Music & concerts",
  museum_exhibition: "Museum & exhibition",
  museum_workshop: "Museum workshop",
  library_workshop: "Library workshop",
  nature_farm: "Nature & farm",
  zoo_animal_park: "Zoo & animal park",
  sports_active: "Sports & active",
  market_food: "Market & food",
  parade_seasonal: "Parade & seasonal",
  film: "Film",
  storytelling: "Storytelling",
  playground_indoor: "Indoor playground",
  guided_tour: "Guided tour",
  holiday_camp: "Holiday camp",
  other: "Other",
};

export const FEATURE_LABELS: Record<FeatureTag, string> = {
  face_painting: "Face painting",
  archery: "Archery",
  bouncy_castle: "Bouncy castle",
  puppet_show: "Puppet show",
  kermis: "Kermis",
  carnaval: "Carnaval",
  food: "Food",
  stories: "Stories",
  costumes: "Costumes",
  animals: "Animals",
  crafts: "Crafts",
  music: "Music",
  science: "Science",
  water_play: "Water play",
  dance: "Dance",
  magic: "Magic",
  treasure_hunt: "Treasure hunt",
  fireworks: "Fireworks",
  parade: "Parade",
  train_ride: "Train ride",
  pumpkin_picking: "Pumpkin picking",
  christmas_market: "Christmas market",
  easter: "Easter",
  halloween: "Halloween",
};

export const FEATURE_EMOJI: Partial<Record<FeatureTag, string>> = {
  face_painting: "🎨",
  archery: "🏹",
  bouncy_castle: "🏰",
  puppet_show: "🎭",
  kermis: "🎡",
  carnaval: "🎉",
  food: "🍟",
  stories: "📖",
  costumes: "🦸",
  animals: "🐐",
  crafts: "✂️",
  music: "🎵",
  science: "🔬",
  water_play: "💦",
  dance: "💃",
  magic: "✨",
  treasure_hunt: "🗺️",
  fireworks: "🎆",
  parade: "🥁",
  train_ride: "🚂",
  pumpkin_picking: "🎃",
  christmas_market: "🎄",
  easter: "🐣",
  halloween: "👻",
};

export const LANGUAGE_LABELS: Record<"nl" | "fr" | "en" | "multi", string> = {
  nl: "Dutch",
  fr: "French",
  en: "English",
  multi: "Bilingual",
};

export const LANGUAGE_EMOJI: Record<"nl" | "fr" | "en" | "multi", string> = {
  nl: "🇳🇱",
  fr: "🇫🇷",
  en: "🇬🇧",
  multi: "🌍",
};
